global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: myapp
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - 192.168.68.104:8080
